version: '3.9'

networks:
  reservaya_network:
    driver: bridge
services:
  db_server:
    image: mariadb:10.5.9
    restart: always
    container_name: '${APP_NAME}-db'
    volumes:
      - ./schemas:/var/lib/mysql:rw
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - reservaya_network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}
      interval: 5s
      retries: 5

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: '${APP_NAME}-db-admin'
    ports:
      - ${APP_DB_ADMIN_PORT}:80
    environment:
      PMA_HOST: db_server
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - reservaya_network

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: '${APP_NAME}-server'
    restart: always
    ports:
      - ${APP_SERVER_PORT}:80
    volumes:
      - ./html:/var/www/html:rw
      - ./config:/usr/local/etc/php
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - reservaya_network
    links:
      - db_server


volumes:
  schemas: {}
  html: {}
  config: {}

