/* ------------------------------------------ */
/* CREACIÓN DE LA BASE DE DATOS */
/* ------------------------------------------ */
DROP DATABASE IF EXISTS RESERVAYA2;
CREATE DATABASE RESERVAYA2;
USE RESERVAYA2;

/* ------------------------------------------ */
/* CREACIÓN DE LAS TABLAS */
/* ------------------------------------------ */

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
ID_USUARIO INT(11) PRIMARY KEY,
NOMBRE_USUARIO VARCHAR(70) NOT NULL,
CLAVE_USUARIO VARCHAR(20) NOT NULL,
TIPO_USUARIO ENUM('Cliente','Empleado','Administrador') NOT NULL,
ESTADO_USUARIO ENUM('Activo','Inactivo') NOT NULL
);


/* ------------------------------------------ */

DROP TABLE IF EXISTS ADMINISTRADOR;
CREATE TABLE ADMINISTRADOR(
ID_ADMIN INT(11) PRIMARY KEY,
NOMBRE_ADMIN VARCHAR(60) NOT NULL,
APELLIDO_ADMIN VARCHAR(60) NOT NULL,
EMAIL_ADMIN VARCHAR(70) UNIQUE NOT NULL,
CELULAR_ADMIN VARCHAR(10) UNIQUE NOT NULL,
ID_USUARIO INT(11) NOT NULL,
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
ON UPDATE CASCADE 
ON DELETE RESTRICT
);

/* ------------------------------------------ */

DROP TABLE IF exists EMPLEADO;
CREATE TABLE EMPLEADO(
ID_EMPLEADO INT(11) PRIMARY KEY,
DOC_EMPLEADO VARCHAR(15) UNIQUE NOT NULL,
NOMBRE_EMPLEADO VARCHAR(60) NOT NULL,
APELLIDO_EMPLEADO VARCHAR(60) NOT NULL,
EMAIL_EMPLEADO VARCHAR(70) UNIQUE NOT NULL,
CELULAR_EMPLEADO VARCHAR(10) UNIQUE NOT NULL,
ID_USUARIO INT(11) NOT NULL,
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
ON UPDATE CASCADE 
ON DELETE RESTRICT
);

/* ------------------------------------------ */

DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE(
ID_CLIENTE INT(11) PRIMARY KEY,
NOMBRE_CLIENTE VARCHAR(60) NOT NULL,
APELLIDO_CLIENTE VARCHAR(60) NOT NULL,
FECHA_NACIMIENTO_CLIENTE DATE NOT NULL,
EMAIL_CLIENTE VARCHAR(70) NOT NULL UNIQUE,
CELULAR_CLIENTE VARCHAR(10) NOT NULL UNIQUE,
ID_USUARIO INT(11) NOT NULL,
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
ON UPDATE CASCADE 
ON DELETE RESTRICT
);

/* ------------------------------------------ */

DROP TABLE IF EXISTS CATEGORIA_PRODUCTO;
CREATE TABLE CATEGORIA_PRODUCTO(
ID_CATEGORIA_PRODUCTO INT(11) PRIMARY KEY,
NOMBRE_CATEGORIA_PRODUCTO CHAR(100)
);

/* ------------------------------------------ */

CREATE TABLE PRODUCTO(
ID_PRODUCTO INT(11) PRIMARY KEY,
ID_CATEGORIA_PRODUCTO INT(11) NOT NULL,
NOMBRE_PRODUCTO VARCHAR(70) NOT NULL,
DESCRIPCION_PRODUCTO VARCHAR(255) NOT NULL,
CANTIDAD_PRODUCTO INT(11) NOT NULL,
VALOR_PRODUCTO REAL NOT NULL,
FOREIGN KEY (ID_CATEGORIA_PRODUCTO) REFERENCES CATEGORIA_PRODUCTO(ID_CATEGORIA_PRODUCTO)
ON UPDATE CASCADE 
ON DELETE RESTRICT
);

/* ------------------------------------------ */

CREATE TABLE USUARIO_VISUALIZA_PRODUCTO(
ID_USUARIO INT(11) NOT NULL,
ID_PRODUCTO INT(11) NOT NULL,
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
ON UPDATE CASCADE 
ON DELETE RESTRICT,
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
ON UPDATE CASCADE 
ON DELETE RESTRICT
);

/* ------------------------------------------ */

DROP TABLE IF exists PROVEEDOR;
CREATE TABLE PROVEEDOR(
ID_PROVEEDOR INT(11) PRIMARY KEY,
NOMBRE_PROVEEDOR VARCHAR(70) NOT NULL,
DIRECCION_PROVEEDOR VARCHAR(100) NOT NULL,
PERSONA_ENCARGADA VARCHAR(70) NOT NULL,
TELEFONO_PROVEEDOR INT(10) NOT NULL
);

/* ------------------------------------------ */

DROP TABLE IF exists CATEGORIA_INSUMO;
CREATE TABLE CATEGORIA_INSUMO(
ID_CATEGORIA_INSUMO INT(11) PRIMARY KEY,
NOMBRE_CATEGORIA_INSUMO VARCHAR(100)
);

/* ------------------------------------------ */

DROP TABLE IF EXISTS INSUMO;
CREATE TABLE INSUMO(
ID_INSUMO INT(11) PRIMARY KEY,
NOMBRE_INSUMO VARCHAR(70) NOT NULL,
CANTIDAD_INSUMO INT(11) NOT NULL,
FECHA_COMPRA_INSUMO DATE NOT NULL,
VALOR_INSUMO DOUBLE NOT NULL,
ID_PROVEEDOR INT(11) NOT NULL,
ID_CATEGORIA_INSUMO INT(11) NOT NULL,
FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
ON UPDATE CASCADE 
ON DELETE RESTRICT,
FOREIGN KEY(ID_CATEGORIA_INSUMO) REFERENCES CATEGORIA_INSUMO(ID_CATEGORIA_INSUMO)
ON UPDATE CASCADE 
ON DELETE RESTRICT
);

/* ------------------------------------------ */

DROP TABLE IF exists USUARIO_ACCEDE_INSUMO;
CREATE TABLE USUARIO_ACCEDE_INSUMO(
ID_USUARIO INT(11) NOT NULL,
ID_INSUMO INT(11) NOT NULL,
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
ON UPDATE CASCADE 
ON DELETE RESTRICT,
FOREIGN KEY (ID_INSUMO) REFERENCES INSUMO(ID_INSUMO)
ON UPDATE CASCADE 
ON DELETE RESTRICT 
);

/* ------------------------------------------ */

DROP TABLE IF exists MESA;
CREATE TABLE MESA(
ID_MESA INT(6) PRIMARY KEY,
CAPACIDAD_MESA INT(2) NOT NULL,
ESTADO_MESA ENUM('Disponible','Ocupada') NOT NULL
);

/* ------------------------------------------ */

DROP TABLE IF EXISTS RESERVACION;
CREATE TABLE RESERVACION(
ID_RESERVACION INT(11) PRIMARY KEY,
ID_CLIENTE INT(11) NOT NULL,
FECHA_RESERVACION DATE NOT NULL,
HORA_RESERVACION TIME NOT NULL,
ESTADO_RESERVACION ENUM('Activa','Completada','Cancelada') NOT NULL,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
ON UPDATE CASCADE 
ON DELETE RESTRICT
);

/* ------------------------------------------ */

DROP TABLE IF exists RESERVACION_RESERVA_MESA;
CREATE TABLE RESERVACION_RESERVA_MESA(
ID_RESERVACION INT(11) NOT NULL,
ID_MESA INT(11) NOT NULL,
FOREIGN KEY(ID_RESERVACION) REFERENCES RESERVACION(ID_RESERVACION)
ON UPDATE CASCADE 
ON DELETE RESTRICT,
FOREIGN KEY(ID_MESA) REFERENCES MESA(ID_MESA)
ON UPDATE CASCADE 
ON DELETE RESTRICT
);

