-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.5.10-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win64
-- HeidiSQL Versión:             11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


/*

_ADMINISTRADOR_
usuario: admin@gmail.com
contraseña: 1234

_EMPLEADO_
usuario: empleado@gmail.com
contraseña: 1234

_CLIENTE_
usuario: cliente@gmail.com
contraseña: 1234


/*
-- Volcando estructura de base de datos para reservaya
CREATE DATABASE IF NOT EXISTS `reservaya` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `reservaya`;

-- Volcando estructura para tabla reservaya.administrador
CREATE TABLE IF NOT EXISTS `administrador` (
  `ID_ADMIN` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_ADMIN` varchar(60) NOT NULL,
  `APELLIDO_ADMIN` varchar(60) NOT NULL,
  `EMAIL_ADMIN` varchar(70) NOT NULL,
  `CELULAR_ADMIN` varchar(10) NOT NULL,
  `ID_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`ID_ADMIN`),
  UNIQUE KEY `EMAIL_ADMIN` (`EMAIL_ADMIN`),
  UNIQUE KEY `CELULAR_ADMIN` (`CELULAR_ADMIN`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `administrador_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuario` (`ID_USUARIO`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.administrador: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `administrador` DISABLE KEYS */;
INSERT INTO `administrador` (`ID_ADMIN`, `NOMBRE_ADMIN`, `APELLIDO_ADMIN`, `EMAIL_ADMIN`, `CELULAR_ADMIN`, `ID_USUARIO`) VALUES
	(1, 'Administrador', 'Reserva Ya', 'admin@reservaya.com', '3112547896', 1);
/*!40000 ALTER TABLE `administrador` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.auditoria_admin
CREATE TABLE IF NOT EXISTS `auditoria_admin` (
  `ID_AUDI` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_ADMIN_ANTERIOR` varchar(60) DEFAULT NULL,
  `APELLIDO_ADMIN_ANTERIOR` varchar(60) DEFAULT NULL,
  `EMAIL_ADMIN_ANTERIOR` varchar(70) DEFAULT NULL,
  `CELULAR_ADMIN_ANTERIOR` varchar(10) DEFAULT NULL,
  `ID_USUARIO_ANTERIOR` int(11) DEFAULT NULL,
  `NOMBRE_ADMIN_NUEVO` varchar(60) DEFAULT NULL,
  `APELLIDO_ADMIN_NUEVO` varchar(60) DEFAULT NULL,
  `EMAIL_ADMIN_NUEVO` varchar(70) DEFAULT NULL,
  `CELULAR_ADMIN_NUEVO` varchar(10) DEFAULT NULL,
  `ID_USUARIO_NUEVO` int(11) DEFAULT NULL,
  `AUDI_FECHA_MODIFICACION` datetime NOT NULL,
  `AUDI_USUARIO` varchar(45) NOT NULL,
  `ID_ADMIN` int(11) NOT NULL,
  `AUDI_ACCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_AUDI`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.auditoria_admin: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `auditoria_admin` DISABLE KEYS */;
INSERT INTO `auditoria_admin` (`ID_AUDI`, `NOMBRE_ADMIN_ANTERIOR`, `APELLIDO_ADMIN_ANTERIOR`, `EMAIL_ADMIN_ANTERIOR`, `CELULAR_ADMIN_ANTERIOR`, `ID_USUARIO_ANTERIOR`, `NOMBRE_ADMIN_NUEVO`, `APELLIDO_ADMIN_NUEVO`, `EMAIL_ADMIN_NUEVO`, `CELULAR_ADMIN_NUEVO`, `ID_USUARIO_NUEVO`, `AUDI_FECHA_MODIFICACION`, `AUDI_USUARIO`, `ID_ADMIN`, `AUDI_ACCION`) VALUES
	(15, NULL, NULL, NULL, NULL, NULL, 'Administrador', 'Reserva Ya', 'admin@reservaya.com', '3112547896', 1, '2021-06-08 13:24:14', 'root@localhost', 1, 'Insercion');
/*!40000 ALTER TABLE `auditoria_admin` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.auditoria_categoria_insumo
CREATE TABLE IF NOT EXISTS `auditoria_categoria_insumo` (
  `ID_AUDI` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_CATEGORIA_INSUMO_ANTERIOR` varchar(100) DEFAULT NULL,
  `NOMBRE_CATEGORIA_INSUMO_NUEVO` varchar(100) DEFAULT NULL,
  `AUDI_FECHA_MODIFICACION` datetime NOT NULL,
  `AUDI_USUARIO` varchar(45) NOT NULL,
  `ID_CATEGORIA_INSUMO` int(11) NOT NULL,
  `AUDI_ACCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_AUDI`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.auditoria_categoria_insumo: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `auditoria_categoria_insumo` DISABLE KEYS */;
/*!40000 ALTER TABLE `auditoria_categoria_insumo` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.auditoria_categoria_producto
CREATE TABLE IF NOT EXISTS `auditoria_categoria_producto` (
  `ID_AUDI` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_CATEGORIA_PRODUCTO_ANTERIOR` varchar(100) DEFAULT NULL,
  `NOMBRE_CATEGORIA_PRODUCTO_NUEVO` varchar(100) DEFAULT NULL,
  `AUDI_FECHA_MODIFICACION` datetime NOT NULL,
  `AUDI_USUARIO` varchar(45) NOT NULL,
  `ID_CATEGORIA_PRODUCTO` int(11) NOT NULL,
  `AUDI_ACCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_AUDI`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.auditoria_categoria_producto: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `auditoria_categoria_producto` DISABLE KEYS */;
/*!40000 ALTER TABLE `auditoria_categoria_producto` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.auditoria_cliente
CREATE TABLE IF NOT EXISTS `auditoria_cliente` (
  `ID_AUDI` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_CLIENTE_ANTERIOR` varchar(60) DEFAULT NULL,
  `APELLIDO_CLIENTE_ANTERIOR` varchar(60) DEFAULT NULL,
  `FECHA_NACIMIENTO_CLIENTE_ANTERIOR` date DEFAULT NULL,
  `EMAIL_CLIENTE_ANTERIOR` varchar(70) DEFAULT NULL,
  `CELULAR_CLIENTE_ANTERIOR` varchar(10) DEFAULT NULL,
  `ID_USUARIO_ANTERIOR` int(11) DEFAULT NULL,
  `NOMBRE_CLIENTE_NUEVO` varchar(60) DEFAULT NULL,
  `APELLIDO_CLIENTE_NUEVO` varchar(60) DEFAULT NULL,
  `FECHA_NACIMIENTO_CLIENTE_NUEVO` date DEFAULT NULL,
  `EMAIL_CLIENTE_NUEVO` varchar(70) DEFAULT NULL,
  `CELULAR_CLIENTE_NUEVO` varchar(10) DEFAULT NULL,
  `ID_USUARIO_NUEVO` int(11) DEFAULT NULL,
  `AUDI_FECHA_MODIFICACION` datetime NOT NULL,
  `AUDI_USUARIO` varchar(45) NOT NULL,
  `ID_CLIENTE` int(11) NOT NULL,
  `AUDI_ACCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_AUDI`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.auditoria_cliente: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `auditoria_cliente` DISABLE KEYS */;
INSERT INTO `auditoria_cliente` (`ID_AUDI`, `NOMBRE_CLIENTE_ANTERIOR`, `APELLIDO_CLIENTE_ANTERIOR`, `FECHA_NACIMIENTO_CLIENTE_ANTERIOR`, `EMAIL_CLIENTE_ANTERIOR`, `CELULAR_CLIENTE_ANTERIOR`, `ID_USUARIO_ANTERIOR`, `NOMBRE_CLIENTE_NUEVO`, `APELLIDO_CLIENTE_NUEVO`, `FECHA_NACIMIENTO_CLIENTE_NUEVO`, `EMAIL_CLIENTE_NUEVO`, `CELULAR_CLIENTE_NUEVO`, `ID_USUARIO_NUEVO`, `AUDI_FECHA_MODIFICACION`, `AUDI_USUARIO`, `ID_CLIENTE`, `AUDI_ACCION`) VALUES
	(12, NULL, NULL, NULL, NULL, NULL, NULL, 'Cliente', 'Reserva Ya', '2000-06-08', 'cliente@gmail.com', '3147895241', 3, '2021-06-08 13:25:10', 'root@localhost', 1, 'Insercion');
/*!40000 ALTER TABLE `auditoria_cliente` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.auditoria_empleado
CREATE TABLE IF NOT EXISTS `auditoria_empleado` (
  `ID_AUDI` int(11) NOT NULL AUTO_INCREMENT,
  `DOC_EMPLEADO_ANTERIOR` varchar(15) DEFAULT NULL,
  `NOMBRE_EMPLEADO_ANTERIOR` varchar(60) DEFAULT NULL,
  `APELLIDO_EMPLEADO_ANTERIOR` varchar(60) DEFAULT NULL,
  `EMAIL_EMPLEADO_ANTERIOR` varchar(70) DEFAULT NULL,
  `CELULAR_EMPLEADO_ANTERIOR` varchar(10) DEFAULT NULL,
  `ID_USUARIO_ANTERIOR` int(11) DEFAULT NULL,
  `DOC_EMPLEADO_NUEVO` varchar(15) DEFAULT NULL,
  `NOMBRE_EMPLEADO_NUEVO` varchar(60) DEFAULT NULL,
  `APELLIDO_EMPLEADO_NUEVO` varchar(60) DEFAULT NULL,
  `EMAIL_EMPLEADO_NUEVO` varchar(70) DEFAULT NULL,
  `CELULAR_EMPLEADO_NUEVO` varchar(10) DEFAULT NULL,
  `ID_USUARIO_NUEVO` int(11) DEFAULT NULL,
  `AUDI_FECHA_MODIFICACION` datetime NOT NULL,
  `AUDI_USUARIO` varchar(45) NOT NULL,
  `ID_EMPLEADO` int(11) NOT NULL,
  `AUDI_ACCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_AUDI`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.auditoria_empleado: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `auditoria_empleado` DISABLE KEYS */;
INSERT INTO `auditoria_empleado` (`ID_AUDI`, `DOC_EMPLEADO_ANTERIOR`, `NOMBRE_EMPLEADO_ANTERIOR`, `APELLIDO_EMPLEADO_ANTERIOR`, `EMAIL_EMPLEADO_ANTERIOR`, `CELULAR_EMPLEADO_ANTERIOR`, `ID_USUARIO_ANTERIOR`, `DOC_EMPLEADO_NUEVO`, `NOMBRE_EMPLEADO_NUEVO`, `APELLIDO_EMPLEADO_NUEVO`, `EMAIL_EMPLEADO_NUEVO`, `CELULAR_EMPLEADO_NUEVO`, `ID_USUARIO_NUEVO`, `AUDI_FECHA_MODIFICACION`, `AUDI_USUARIO`, `ID_EMPLEADO`, `AUDI_ACCION`) VALUES
	(8, NULL, NULL, NULL, NULL, NULL, NULL, '47851478', 'Empleado', 'Reserva Ya', 'empleado@reservaya.com', '3178456985', 2, '2021-06-08 13:25:53', 'root@localhost', 1, 'Insercion');
/*!40000 ALTER TABLE `auditoria_empleado` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.auditoria_insumo
CREATE TABLE IF NOT EXISTS `auditoria_insumo` (
  `ID_AUDI` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_INSUMO_ANTERIOR` varchar(70) DEFAULT NULL,
  `CANTIDAD_INSUMO_ANTERIOR` int(11) DEFAULT NULL,
  `FECHA_COMPRA_INSUMO_ANTERIOR` date DEFAULT NULL,
  `VALOR_INSUMO_ANTERIOR` double DEFAULT NULL,
  `ID_PROVEEDOR_ANTERIOR` int(11) DEFAULT NULL,
  `ID_CATEGORIA_INSUMO_ANTERIOR` int(11) DEFAULT NULL,
  `NOMBRE_INSUMO_NUEVO` varchar(70) DEFAULT NULL,
  `CANTIDAD_INSUMO_NUEVO` int(11) DEFAULT NULL,
  `FECHA_COMPRA_INSUMO_NUEVO` date DEFAULT NULL,
  `VALOR_INSUMO_NUEVO` double DEFAULT NULL,
  `ID_PROVEEDOR_NUEVO` int(11) DEFAULT NULL,
  `ID_CATEGORIA_INSUMO_NUEVO` int(11) DEFAULT NULL,
  `AUDI_FECHA_MODIFICACION` datetime NOT NULL,
  `AUDI_USUARIO` varchar(45) NOT NULL,
  `ID_INSUMO` int(11) NOT NULL,
  `AUDI_ACCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_AUDI`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.auditoria_insumo: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `auditoria_insumo` DISABLE KEYS */;
/*!40000 ALTER TABLE `auditoria_insumo` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.auditoria_mesa
CREATE TABLE IF NOT EXISTS `auditoria_mesa` (
  `ID_AUDI` int(11) NOT NULL AUTO_INCREMENT,
  `CAPACIDAD_MESA_ANTERIOR` int(2) DEFAULT NULL,
  `ESTADO_MESA_ANTERIOR` enum('Disponible','Ocupada') DEFAULT NULL,
  `CAPACIDAD_MESA_NUEVA` int(2) DEFAULT NULL,
  `ESTADO_MESA_NUEVA` enum('Disponible','Ocupada') DEFAULT NULL,
  `AUDI_FECHA_MODIFICACION` datetime NOT NULL,
  `AUDI_USUARIO` varchar(45) NOT NULL,
  `ID_MESA` int(11) NOT NULL,
  `AUDI_ACCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_AUDI`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.auditoria_mesa: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `auditoria_mesa` DISABLE KEYS */;
/*!40000 ALTER TABLE `auditoria_mesa` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.auditoria_producto
CREATE TABLE IF NOT EXISTS `auditoria_producto` (
  `ID_AUDI` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CATEGORIA_PRODUCTO_ANTERIOR` int(11) DEFAULT NULL,
  `NOMBRE_PRODUCTO_ANTERIOR` varchar(70) DEFAULT NULL,
  `DESCRIPCION_PRODUCTO_ANTERIOR` varchar(255) DEFAULT NULL,
  `CANTIDAD_PRODUCTO_ANTERIOR` int(11) DEFAULT NULL,
  `VALOR_PRODUCTO_ANTERIOR` double DEFAULT NULL,
  `IMAGEN_PRODUCTO_ANTERIOR` varchar(255) DEFAULT NULL,
  `ID_CATEGORIA_PRODUCTO_NUEVO` int(11) DEFAULT NULL,
  `NOMBRE_PRODUCTO_NUEVO` varchar(70) DEFAULT NULL,
  `DESCRIPCION_PRODUCTO_NUEVO` varchar(255) DEFAULT NULL,
  `CANTIDAD_PRODUCTO_NUEVO` int(11) DEFAULT NULL,
  `VALOR_PRODUCTO_NUEVO` double DEFAULT NULL,
  `IMAGEN_PRODUCTO_NUEVO` varchar(255) DEFAULT NULL,
  `AUDI_FECHA_MODIFICACION` datetime NOT NULL,
  `AUDI_USUARIO` varchar(45) NOT NULL,
  `ID_PRODUCTO` int(11) NOT NULL,
  `AUDI_ACCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_AUDI`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.auditoria_producto: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `auditoria_producto` DISABLE KEYS */;
/*!40000 ALTER TABLE `auditoria_producto` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.auditoria_proveedor
CREATE TABLE IF NOT EXISTS `auditoria_proveedor` (
  `ID_AUDI` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_PROVEEDOR_ANTERIOR` varchar(70) DEFAULT NULL,
  `DIRECCION_PROVEEDOR_ANTERIOR` varchar(100) DEFAULT NULL,
  `PERSONA_ENCARGADA_ANTERIOR` varchar(70) DEFAULT NULL,
  `TELEFONO_PROVEEDOR_ANTERIOR` int(10) DEFAULT NULL,
  `NOMBRE_PROVEEDOR_NUEVO` varchar(70) DEFAULT NULL,
  `DIRECCION_PROVEEDOR_NUEVO` varchar(100) DEFAULT NULL,
  `PERSONA_ENCARGADA_NUEVO` varchar(70) DEFAULT NULL,
  `TELEFONO_PROVEEDOR_NUEVO` int(10) DEFAULT NULL,
  `AUDI_FECHA_MODIFICACION` datetime NOT NULL,
  `AUDI_USUARIO` varchar(45) NOT NULL,
  `ID_PROVEEDOR` int(11) NOT NULL,
  `AUDI_ACCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_AUDI`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.auditoria_proveedor: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `auditoria_proveedor` DISABLE KEYS */;
/*!40000 ALTER TABLE `auditoria_proveedor` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.auditoria_reservacion
CREATE TABLE IF NOT EXISTS `auditoria_reservacion` (
  `ID_AUDI` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE_ANTERIOR` int(11) DEFAULT NULL,
  `FECHA_RESERVACION_ANTERIOR` date DEFAULT NULL,
  `HORA_RESERVACION_ANTERIOR` time DEFAULT NULL,
  `ESTADO_RESERVACION_ANTERIOR` enum('Activa','Completada','Cancelada') DEFAULT NULL,
  `ASIENTO_ANTERIOR` int(2) DEFAULT NULL,
  `ID_CLIENTE_NUEVO` int(11) DEFAULT NULL,
  `FECHA_RESERVACION_NUEVO` date DEFAULT NULL,
  `HORA_RESERVACION_NUEVO` time DEFAULT NULL,
  `ESTADO_RESERVACION_NUEVO` enum('Activa','Completada','Cancelada') DEFAULT NULL,
  `ASIENTO_NUEVO` int(2) DEFAULT NULL,
  `AUDI_FECHA_MODIFICACION` datetime NOT NULL,
  `AUDI_USUARIO` varchar(45) NOT NULL,
  `ID_RESERVACION` int(11) NOT NULL,
  `AUDI_ACCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_AUDI`)
) ENGINE=InnoDB AUTO_INCREMENT=555 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.auditoria_reservacion: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `auditoria_reservacion` DISABLE KEYS */;
/*!40000 ALTER TABLE `auditoria_reservacion` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.auditoria_reservacion_reserva_mesa
CREATE TABLE IF NOT EXISTS `auditoria_reservacion_reserva_mesa` (
  `ID_AUDI` int(11) NOT NULL AUTO_INCREMENT,
  `ID_RESERVACION_ANTERIOR` int(11) DEFAULT NULL,
  `ID_MESA_ANTERIOR` int(11) DEFAULT NULL,
  `ID_RESERVACION_NUEVO` int(11) DEFAULT NULL,
  `ID_MESA_NUEVO` int(11) DEFAULT NULL,
  `AUDI_FECHA_MODIFICACION` datetime NOT NULL,
  `AUDI_USUARIO` varchar(45) NOT NULL,
  `ID_RESERVACION_RESERVA_MESA` int(11) NOT NULL,
  `AUDI_ACCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_AUDI`)
) ENGINE=InnoDB AUTO_INCREMENT=128 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.auditoria_reservacion_reserva_mesa: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `auditoria_reservacion_reserva_mesa` DISABLE KEYS */;
/*!40000 ALTER TABLE `auditoria_reservacion_reserva_mesa` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.auditoria_usuario
CREATE TABLE IF NOT EXISTS `auditoria_usuario` (
  `ID_AUDI` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_USUARIO_ANTERIOR` varchar(70) DEFAULT NULL,
  `CLAVE_USUARIO_ANTERIOR` varchar(255) DEFAULT NULL,
  `TIPO_USUARIO_ANTERIOR` enum('Cliente','Empleado','Administrador') DEFAULT NULL,
  `ESTADO_USUARIO_ANTERIOR` enum('Activo','Inactivo') DEFAULT NULL,
  `FOTO_PERFIL_ANTERIOR` varchar(255) DEFAULT NULL,
  `NOMBRE_USUARIO_NUEVO` varchar(70) DEFAULT NULL,
  `CLAVE_USUARIO_NUEVO` varchar(255) DEFAULT NULL,
  `TIPO_USUARIO_NUEVO` enum('Cliente','Empleado','Administrador') DEFAULT NULL,
  `ESTADO_USUARIO_NUEVO` enum('Activo','Inactivo') DEFAULT NULL,
  `FOTO_PERFIL_NUEVO` varchar(255) DEFAULT NULL,
  `AUDI_FECHA_MODIFICACION` datetime NOT NULL,
  `AUDI_USUARIO` varchar(45) NOT NULL,
  `ID_USUARIO` int(11) NOT NULL,
  `AUDI_ACCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_AUDI`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.auditoria_usuario: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `auditoria_usuario` DISABLE KEYS */;
INSERT INTO `auditoria_usuario` (`ID_AUDI`, `NOMBRE_USUARIO_ANTERIOR`, `CLAVE_USUARIO_ANTERIOR`, `TIPO_USUARIO_ANTERIOR`, `ESTADO_USUARIO_ANTERIOR`, `FOTO_PERFIL_ANTERIOR`, `NOMBRE_USUARIO_NUEVO`, `CLAVE_USUARIO_NUEVO`, `TIPO_USUARIO_NUEVO`, `ESTADO_USUARIO_NUEVO`, `FOTO_PERFIL_NUEVO`, `AUDI_FECHA_MODIFICACION`, `AUDI_USUARIO`, `ID_USUARIO`, `AUDI_ACCION`) VALUES
	(34, NULL, NULL, NULL, NULL, NULL, 'admin@gmail.com', '$2y$10$C9gbqEXD1ZMaRpZ.8RERk.qzE5yNnjO5olg5y.giNzyMHI6tqlIkm', 'Administrador', 'Activo', '.', '2021-06-08 13:22:55', 'root@localhost', 1, 'Insercion'),
	(36, NULL, NULL, NULL, NULL, NULL, 'empleado@gmail.com', '$2y$10$O1V6G4j.RHNsPegZ9QTaw.NdTL7PQy/quAlD9O1XmpicZ0IkB0KXq', 'Empleado', 'Activo', '.', '2021-06-08 13:23:18', 'root@localhost', 2, 'Insercion'),
	(37, NULL, NULL, NULL, NULL, NULL, 'cliente@gmail.com', '$2y$10$KO4IpwfevK5LgqsSnuM/3.0oxEg81z2al6ZOrctrfhgAbsqJmoVpO', 'Cliente', 'Activo', '.', '2021-06-08 13:23:40', 'root@localhost', 3, 'Insercion');
/*!40000 ALTER TABLE `auditoria_usuario` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.categoria_insumo
CREATE TABLE IF NOT EXISTS `categoria_insumo` (
  `ID_CATEGORIA_INSUMO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_CATEGORIA_INSUMO` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_CATEGORIA_INSUMO`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.categoria_insumo: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `categoria_insumo` DISABLE KEYS */;
/*!40000 ALTER TABLE `categoria_insumo` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.categoria_producto
CREATE TABLE IF NOT EXISTS `categoria_producto` (
  `ID_CATEGORIA_PRODUCTO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_CATEGORIA_PRODUCTO` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_CATEGORIA_PRODUCTO`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.categoria_producto: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `categoria_producto` DISABLE KEYS */;
/*!40000 ALTER TABLE `categoria_producto` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.cliente
CREATE TABLE IF NOT EXISTS `cliente` (
  `ID_CLIENTE` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_CLIENTE` varchar(60) NOT NULL,
  `APELLIDO_CLIENTE` varchar(60) NOT NULL,
  `FECHA_NACIMIENTO_CLIENTE` date NOT NULL,
  `EMAIL_CLIENTE` varchar(70) NOT NULL,
  `CELULAR_CLIENTE` varchar(10) NOT NULL,
  `ID_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`ID_CLIENTE`),
  UNIQUE KEY `EMAIL_CLIENTE` (`EMAIL_CLIENTE`),
  UNIQUE KEY `CELULAR_CLIENTE` (`CELULAR_CLIENTE`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `cliente_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuario` (`ID_USUARIO`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.cliente: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `cliente` DISABLE KEYS */;
INSERT INTO `cliente` (`ID_CLIENTE`, `NOMBRE_CLIENTE`, `APELLIDO_CLIENTE`, `FECHA_NACIMIENTO_CLIENTE`, `EMAIL_CLIENTE`, `CELULAR_CLIENTE`, `ID_USUARIO`) VALUES
	(1, 'Cliente', 'Reserva Ya', '2000-06-08', 'cliente@gmail.com', '3147895241', 3);
/*!40000 ALTER TABLE `cliente` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.empleado
CREATE TABLE IF NOT EXISTS `empleado` (
  `ID_EMPLEADO` int(11) NOT NULL AUTO_INCREMENT,
  `DOC_EMPLEADO` varchar(15) NOT NULL,
  `NOMBRE_EMPLEADO` varchar(60) NOT NULL,
  `APELLIDO_EMPLEADO` varchar(60) NOT NULL,
  `EMAIL_EMPLEADO` varchar(70) NOT NULL,
  `CELULAR_EMPLEADO` varchar(10) NOT NULL,
  `ID_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`ID_EMPLEADO`),
  UNIQUE KEY `DOC_EMPLEADO` (`DOC_EMPLEADO`),
  UNIQUE KEY `EMAIL_EMPLEADO` (`EMAIL_EMPLEADO`),
  UNIQUE KEY `CELULAR_EMPLEADO` (`CELULAR_EMPLEADO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `empleado_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuario` (`ID_USUARIO`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.empleado: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `empleado` DISABLE KEYS */;
INSERT INTO `empleado` (`ID_EMPLEADO`, `DOC_EMPLEADO`, `NOMBRE_EMPLEADO`, `APELLIDO_EMPLEADO`, `EMAIL_EMPLEADO`, `CELULAR_EMPLEADO`, `ID_USUARIO`) VALUES
	(1, '47851478', 'Empleado', 'Reserva Ya', 'empleado@reservaya.com', '3178456985', 2);
/*!40000 ALTER TABLE `empleado` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.insumo
CREATE TABLE IF NOT EXISTS `insumo` (
  `ID_INSUMO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_INSUMO` varchar(70) NOT NULL,
  `CANTIDAD_INSUMO` int(11) NOT NULL,
  `FECHA_COMPRA_INSUMO` date NOT NULL,
  `VALOR_INSUMO` double NOT NULL,
  `ID_PROVEEDOR` int(11) NOT NULL,
  `ID_CATEGORIA_INSUMO` int(11) NOT NULL,
  PRIMARY KEY (`ID_INSUMO`),
  KEY `ID_PROVEEDOR` (`ID_PROVEEDOR`),
  KEY `ID_CATEGORIA_INSUMO` (`ID_CATEGORIA_INSUMO`),
  CONSTRAINT `insumo_ibfk_1` FOREIGN KEY (`ID_PROVEEDOR`) REFERENCES `proveedor` (`ID_PROVEEDOR`) ON UPDATE CASCADE,
  CONSTRAINT `insumo_ibfk_2` FOREIGN KEY (`ID_CATEGORIA_INSUMO`) REFERENCES `categoria_insumo` (`ID_CATEGORIA_INSUMO`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.insumo: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `insumo` DISABLE KEYS */;
/*!40000 ALTER TABLE `insumo` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.mesa
CREATE TABLE IF NOT EXISTS `mesa` (
  `ID_MESA` int(6) NOT NULL AUTO_INCREMENT,
  `CAPACIDAD_MESA` int(2) NOT NULL,
  `ESTADO_MESA` enum('Disponible','Ocupada') NOT NULL,
  PRIMARY KEY (`ID_MESA`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.mesa: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `mesa` DISABLE KEYS */;
/*!40000 ALTER TABLE `mesa` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.producto
CREATE TABLE IF NOT EXISTS `producto` (
  `ID_PRODUCTO` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CATEGORIA_PRODUCTO` int(11) NOT NULL,
  `NOMBRE_PRODUCTO` varchar(70) NOT NULL,
  `DESCRIPCION_PRODUCTO` varchar(255) NOT NULL,
  `CANTIDAD_PRODUCTO` int(11) NOT NULL,
  `VALOR_PRODUCTO` double NOT NULL,
  `IMAGEN_PRODUCTO` varchar(255) NOT NULL,
  PRIMARY KEY (`ID_PRODUCTO`),
  KEY `ID_CATEGORIA_PRODUCTO` (`ID_CATEGORIA_PRODUCTO`),
  KEY `verProducto` (`ID_PRODUCTO`,`NOMBRE_PRODUCTO`,`VALOR_PRODUCTO`),
  CONSTRAINT `producto_ibfk_1` FOREIGN KEY (`ID_CATEGORIA_PRODUCTO`) REFERENCES `categoria_producto` (`ID_CATEGORIA_PRODUCTO`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.producto: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `producto` DISABLE KEYS */;
/*!40000 ALTER TABLE `producto` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.proveedor
CREATE TABLE IF NOT EXISTS `proveedor` (
  `ID_PROVEEDOR` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_PROVEEDOR` varchar(70) NOT NULL,
  `DIRECCION_PROVEEDOR` varchar(100) NOT NULL,
  `PERSONA_ENCARGADA` varchar(70) NOT NULL,
  `TELEFONO_PROVEEDOR` varchar(10) NOT NULL,
  PRIMARY KEY (`ID_PROVEEDOR`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.proveedor: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `proveedor` DISABLE KEYS */;
/*!40000 ALTER TABLE `proveedor` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.reservacion
CREATE TABLE IF NOT EXISTS `reservacion` (
  `ID_RESERVACION` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE` int(11) NOT NULL,
  `FECHA_RESERVACION` date NOT NULL,
  `HORA_RESERVACION` time NOT NULL,
  `ESTADO_RESERVACION` enum('Activa','Completada','Cancelada') NOT NULL,
  `ASIENTO` int(2) NOT NULL,
  PRIMARY KEY (`ID_RESERVACION`),
  KEY `ID_CLIENTE` (`ID_CLIENTE`),
  CONSTRAINT `reservacion_ibfk_1` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID_CLIENTE`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=253 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.reservacion: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `reservacion` DISABLE KEYS */;
/*!40000 ALTER TABLE `reservacion` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.reservacion_reserva_mesa
CREATE TABLE IF NOT EXISTS `reservacion_reserva_mesa` (
  `ID_RESERVACION_RESERVA_MESA` int(11) NOT NULL AUTO_INCREMENT,
  `ID_RESERVACION` int(11) NOT NULL,
  `ID_MESA` int(11) NOT NULL,
  PRIMARY KEY (`ID_RESERVACION_RESERVA_MESA`),
  KEY `ID_RESERVACION` (`ID_RESERVACION`),
  KEY `ID_MESA` (`ID_MESA`),
  CONSTRAINT `reservacion_reserva_mesa_ibfk_1` FOREIGN KEY (`ID_RESERVACION`) REFERENCES `reservacion` (`ID_RESERVACION`) ON UPDATE CASCADE,
  CONSTRAINT `reservacion_reserva_mesa_ibfk_2` FOREIGN KEY (`ID_MESA`) REFERENCES `mesa` (`ID_MESA`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=218 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.reservacion_reserva_mesa: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `reservacion_reserva_mesa` DISABLE KEYS */;
/*!40000 ALTER TABLE `reservacion_reserva_mesa` ENABLE KEYS */;

-- Volcando estructura para tabla reservaya.usuario
CREATE TABLE IF NOT EXISTS `usuario` (
  `ID_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_USUARIO` varchar(70) NOT NULL,
  `CLAVE_USUARIO` varchar(255) NOT NULL,
  `TIPO_USUARIO` enum('Cliente','Empleado','Administrador') NOT NULL,
  `ESTADO_USUARIO` enum('Activo','Inactivo') NOT NULL,
  `FOTO_PERFIL` varchar(255) NOT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  UNIQUE KEY `NOMBRE_USUARIO` (`NOMBRE_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla reservaya.usuario: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `usuario` DISABLE KEYS */;
INSERT INTO `usuario` (`ID_USUARIO`, `NOMBRE_USUARIO`, `CLAVE_USUARIO`, `TIPO_USUARIO`, `ESTADO_USUARIO`, `FOTO_PERFIL`) VALUES
	(1, 'admin@gmail.com', '$2y$10$C9gbqEXD1ZMaRpZ.8RERk.qzE5yNnjO5olg5y.giNzyMHI6tqlIkm', 'Administrador', 'Activo', '.'),
	(2, 'empleado@gmail.com', '$2y$10$O1V6G4j.RHNsPegZ9QTaw.NdTL7PQy/quAlD9O1XmpicZ0IkB0KXq', 'Empleado', 'Activo', '.'),
	(3, 'cliente@gmail.com', '$2y$10$KO4IpwfevK5LgqsSnuM/3.0oxEg81z2al6ZOrctrfhgAbsqJmoVpO', 'Cliente', 'Activo', '.');
/*!40000 ALTER TABLE `usuario` ENABLE KEYS */;

-- Volcando estructura para disparador reservaya.AUDITORIA_DELETE_ADMIN
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_DELETE_ADMIN after delete on administrador
for each row
insert into AUDITORIA_ADMIN
(NOMBRE_ADMIN_ANTERIOR,
APELLIDO_ADMIN_ANTERIOR,
EMAIL_ADMIN_ANTERIOR,
CELULAR_ADMIN_ANTERIOR,
ID_USUARIO_ANTERIOR,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_ADMIN,
AUDI_ACCION
)
values
(old.NOMBRE_ADMIN,old.APELLIDO_ADMIN,old.EMAIL_ADMIN,old.CELULAR_ADMIN,old.ID_USUARIO,
now(),current_user(),old.ID_ADMIN,'Eliminar')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_DELETE_CATEGORIA_INSUMO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_DELETE_CATEGORIA_INSUMO after delete on CATEGORIA_INSUMO
for each row
insert into AUDITORIA_CATEGORIA_INSUMO
(NOMBRE_CATEGORIA_INSUMO_ANTERIOR,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_CATEGORIA_INSUMO,
AUDI_ACCION
)
values
(old.NOMBRE_CATEGORIA_INSUMO,
now(),current_user(),old.ID_CATEGORIA_INSUMO,'Eliminar')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_DELETE_CATEGORIA_PRODUCTO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_DELETE_CATEGORIA_PRODUCTO after delete on categoria_producto
for each row
insert into AUDITORIA_CATEGORIA_PRODUCTO
(NOMBRE_CATEGORIA_PRODUCTO_ANTERIOR,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_CATEGORIA_PRODUCTO,
AUDI_ACCION
)
values
(old.NOMBRE_CATEGORIA_PRODUCTO,
now(),current_user(),old.ID_CATEGORIA_PRODUCTO,'Eliminar')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_DELETE_CLIENTE
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_DELETE_CLIENTE after delete on cliente
for each row
insert into AUDITORIA_CLIENTE
(NOMBRE_CLIENTE_ANTERIOR,
APELLIDO_CLIENTE_ANTERIOR,
FECHA_NACIMIENTO_CLIENTE_ANTERIOR,
EMAIL_CLIENTE_ANTERIOR,
CELULAR_CLIENTE_ANTERIOR,
ID_USUARIO_ANTERIOR,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_CLIENTE,
AUDI_ACCION
)
values
(old.NOMBRE_CLIENTE,old.APELLIDO_CLIENTE,old.FECHA_NACIMIENTO_CLIENTE,old.EMAIL_CLIENTE,old.CELULAR_CLIENTE,old.ID_USUARIO,
now(),current_user(),old.ID_CLIENTE,'Eliminar')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_DELETE_EMPLEADO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_DELETE_EMPLEADO after delete on empleado
for each row
insert into AUDITORIA_EMPLEADO
(DOC_EMPLEADO_ANTERIOR,
NOMBRE_EMPLEADO_ANTERIOR,
APELLIDO_EMPLEADO_ANTERIOR,
EMAIL_EMPLEADO_ANTERIOR,
CELULAR_EMPLEADO_ANTERIOR,
ID_USUARIO_ANTERIOR,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_EMPLEADO,
AUDI_ACCION
)
values
(old.DOC_EMPLEADO,old.NOMBRE_EMPLEADO,old.APELLIDO_EMPLEADO,old.EMAIL_EMPLEADO,old.CELULAR_EMPLEADO,old.ID_USUARIO,
now(),current_user(),old.ID_EMPLEADO,'Eliminar')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_DELETE_INSUMO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_DELETE_INSUMO after delete on insumo
for each row
insert into AUDITORIA_INSUMO
(NOMBRE_INSUMO_ANTERIOR,
CANTIDAD_INSUMO_ANTERIOR,
FECHA_COMPRA_INSUMO_ANTERIOR,
VALOR_INSUMO_ANTERIOR,
ID_PROVEEDOR_ANTERIOR,
ID_CATEGORIA_INSUMO_ANTERIOR,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_INSUMO,
AUDI_ACCION
)
values
(old.NOMBRE_INSUMO,old.CANTIDAD_INSUMO,old.FECHA_COMPRA_INSUMO,old.VALOR_INSUMO,old.ID_PROVEEDOR,old.ID_CATEGORIA_INSUMO,
now(),current_user(),old.ID_INSUMO,'Eliminar')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_DELETE_MESA
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_DELETE_MESA AFTER DELETE on MESA
for each row
insert into AUDITORIA_MESA
(CAPACIDAD_MESA_ANTERIOR,
ESTADO_MESA_ANTERIOR,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_MESA,
AUDI_ACCION
)
values
(old.CAPACIDAD_MESA ,old.ESTADO_MESA,
now(),current_user(),old.ID_MESA,'ELIMINAR')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_DELETE_PRODUCTO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_DELETE_PRODUCTO after delete on producto
for each row
insert into AUDITORIA_PRODUCTO
(ID_CATEGORIA_PRODUCTO_ANTERIOR,
NOMBRE_PRODUCTO_ANTERIOR,
DESCRIPCION_PRODUCTO_ANTERIOR,
CANTIDAD_PRODUCTO_ANTERIOR,
VALOR_PRODUCTO_ANTERIOR,
IMAGEN_PRODUCTO_ANTERIOR,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_PRODUCTO,
AUDI_ACCION
)
values
(old.ID_CATEGORIA_PRODUCTO,old.NOMBRE_PRODUCTO,old.DESCRIPCION_PRODUCTO,old.CANTIDAD_PRODUCTO,old.VALOR_PRODUCTO,old.IMAGEN_PRODUCTO,
now(),current_user(),old.ID_PRODUCTO,'Eliminar')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_DELETE_PROVEEDOR
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_DELETE_PROVEEDOR after delete on proveedor
for each row
insert into AUDITORIA_PROVEEDOR
(NOMBRE_PROVEEDOR_ANTERIOR,
DIRECCION_PROVEEDOR_ANTERIOR,
PERSONA_ENCARGADA_ANTERIOR,
TELEFONO_PROVEEDOR_ANTERIOR,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_PROVEEDOR,
AUDI_ACCION
)
values
(old.NOMBRE_PROVEEDOR,old.DIRECCION_PROVEEDOR,old.PERSONA_ENCARGADA,old.TELEFONO_PROVEEDOR,
now(),current_user(),old.ID_PROVEEDOR,'Eliminar')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_DELETE_RESERVACION
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_DELETE_RESERVACION AFTER DELETE on RESERVACION
for each row
insert into AUDITORIA_RESERVACION
(ID_CLIENTE_ANTERIOR,
FECHA_RESERVACION_ANTERIOR,
HORA_RESERVACION_ANTERIOR,
ESTADO_RESERVACION_ANTERIOR,
ASIENTO_ANTERIOR,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_RESERVACION,
AUDI_ACCION
)
values
(old.ID_CLIENTE,old.FECHA_RESERVACION ,old.HORA_RESERVACION,old.ESTADO_RESERVACION,old.ASIENTO,
now(),current_user(),old.ID_RESERVACION ,'Eliminar')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_DELETE_RESERVACION_RESERVA_MESA
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_DELETE_RESERVACION_RESERVA_MESA after delete on RESERVACION_RESERVA_MESA
for each row
insert into AUDITORIA_RESERVACION_RESERVA_MESA
(ID_RESERVACION_ANTERIOR,
ID_MESA_ANTERIOR,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_RESERVACION_RESERVA_MESA,
AUDI_ACCION
)
values
(old.ID_RESERVACION,old.ID_MESA,
now(),current_user(),old.ID_RESERVACION_RESERVA_MESA ,'Eliminar')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_DELETE_USUARIO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_DELETE_USUARIO after delete on usuario
for each row
insert into AUDITORIA_USUARIO
(NOMBRE_USUARIO_ANTERIOR,
CLAVE_USUARIO_ANTERIOR,
TIPO_USUARIO_ANTERIOR,
ESTADO_USUARIO_ANTERIOR,
FOTO_PERFIL_ANTERIOR,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_USUARIO,
AUDI_ACCION
)
values
(old.NOMBRE_USUARIO,old.CLAVE_USUARIO,old.TIPO_USUARIO,old.ESTADO_USUARIO,old.FOTO_PERFIL,
now(),current_user(),old.ID_USUARIO,'Eliminar')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_INSERT_ADMIN
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_INSERT_ADMIN before insert on administrador
for each row
insert into AUDITORIA_ADMIN
(NOMBRE_ADMIN_NUEVO,
APELLIDO_ADMIN_NUEVO,
EMAIL_ADMIN_NUEVO,
CELULAR_ADMIN_NUEVO,
ID_USUARIO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_ADMIN,
AUDI_ACCION
)
values
(new.NOMBRE_ADMIN,new.APELLIDO_ADMIN,new.EMAIL_ADMIN,new.CELULAR_ADMIN,new.ID_USUARIO,
now(),current_user(),new.ID_ADMIN,'Insercion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_INSERT_CATEGORIA_INSUMO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_INSERT_CATEGORIA_INSUMO before insert on CATEGORIA_INSUMO
for each row
insert into AUDITORIA_CATEGORIA_INSUMO
(NOMBRE_CATEGORIA_INSUMO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_CATEGORIA_INSUMO,
AUDI_ACCION
)
values
(new.NOMBRE_CATEGORIA_INSUMO,
now(),current_user(),new.ID_CATEGORIA_INSUMO,'Insercion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_INSERT_CATEGORIA_PRODUCTO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_INSERT_CATEGORIA_PRODUCTO before insert on categoria_producto
for each row
insert into AUDITORIA_CATEGORIA_PRODUCTO
(NOMBRE_CATEGORIA_PRODUCTO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_CATEGORIA_PRODUCTO,
AUDI_ACCION
)
values
(new.NOMBRE_CATEGORIA_PRODUCTO,
now(),current_user(),new.ID_CATEGORIA_PRODUCTO,'Insercion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_INSERT_CLIENTE
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_INSERT_CLIENTE before insert on cliente
for each row
insert into AUDITORIA_CLIENTE
(NOMBRE_CLIENTE_NUEVO,
APELLIDO_CLIENTE_NUEVO,
FECHA_NACIMIENTO_CLIENTE_NUEVO,
EMAIL_CLIENTE_NUEVO,
CELULAR_CLIENTE_NUEVO,
ID_USUARIO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_CLIENTE,
AUDI_ACCION
)
values
(new.NOMBRE_CLIENTE,new.APELLIDO_CLIENTE,new.FECHA_NACIMIENTO_CLIENTE,new.EMAIL_CLIENTE,new.CELULAR_CLIENTE,new.ID_USUARIO,
now(),current_user(),new.ID_CLIENTE,'Insercion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_INSERT_EMPLEADO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_INSERT_EMPLEADO before insert on empleado
for each row
insert into AUDITORIA_EMPLEADO
(DOC_EMPLEADO_NUEVO,
NOMBRE_EMPLEADO_NUEVO,
APELLIDO_EMPLEADO_NUEVO,
EMAIL_EMPLEADO_NUEVO,
CELULAR_EMPLEADO_NUEVO,
ID_USUARIO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_EMPLEADO,
AUDI_ACCION
)
values
(new.DOC_EMPLEADO,new.NOMBRE_EMPLEADO,new.APELLIDO_EMPLEADO,new.EMAIL_EMPLEADO,new.CELULAR_EMPLEADO,new.ID_USUARIO,
now(),current_user(),new.ID_EMPLEADO,'Insercion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_INSERT_INSUMO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_INSERT_INSUMO before insert on insumo
for each row
insert into AUDITORIA_INSUMO
(NOMBRE_INSUMO_NUEVO,
CANTIDAD_INSUMO_NUEVO,
FECHA_COMPRA_INSUMO_NUEVO,
VALOR_INSUMO_NUEVO,
ID_PROVEEDOR_NUEVO,
ID_CATEGORIA_INSUMO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_INSUMO,
AUDI_ACCION
)
values
(new.NOMBRE_INSUMO,new.CANTIDAD_INSUMO,new.FECHA_COMPRA_INSUMO,new.VALOR_INSUMO,new.ID_PROVEEDOR,new.ID_CATEGORIA_INSUMO,
now(),current_user(),new.ID_INSUMO,'Insercion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_INSERT_MESA
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_INSERT_MESA before insert on MESA
for each row
insert into AUDITORIA_MESA
(
CAPACIDAD_MESA_NUEVA,
ESTADO_MESA_NUEVA,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_MESA,
AUDI_ACCION
)
values
(new.CAPACIDAD_MESA,new.ESTADO_MESA,
now(),current_user(),new.ID_MESA,'Insercion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_INSERT_PRODUCTO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_INSERT_PRODUCTO before insert on producto
for each row
insert into AUDITORIA_PRODUCTO
(ID_CATEGORIA_PRODUCTO_NUEVO,
NOMBRE_PRODUCTO_NUEVO,
DESCRIPCION_PRODUCTO_NUEVO,
CANTIDAD_PRODUCTO_NUEVO,
VALOR_PRODUCTO_NUEVO,
IMAGEN_PRODUCTO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_PRODUCTO,
AUDI_ACCION
)
values
(new.ID_CATEGORIA_PRODUCTO,new.NOMBRE_PRODUCTO,new.DESCRIPCION_PRODUCTO,new.CANTIDAD_PRODUCTO,new.VALOR_PRODUCTO,new.IMAGEN_PRODUCTO,
now(),current_user(),new.ID_PRODUCTO,'Insercion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_INSERT_PROVEEDOR
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_INSERT_PROVEEDOR before insert on proveedor
for each row
insert into AUDITORIA_PROVEEDOR
(NOMBRE_PROVEEDOR_NUEVO,
DIRECCION_PROVEEDOR_NUEVO,
PERSONA_ENCARGADA_NUEVO,
TELEFONO_PROVEEDOR_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_PROVEEDOR,
AUDI_ACCION
)
values
(new.NOMBRE_PROVEEDOR,new.DIRECCION_PROVEEDOR,new.PERSONA_ENCARGADA,new.TELEFONO_PROVEEDOR,
now(),current_user(),new.ID_PROVEEDOR,'Insercion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_INSERT_RESERVACION
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_INSERT_RESERVACION before INSERT on RESERVACION
for each row
insert into AUDITORIA_RESERVACION
(
ID_CLIENTE_NUEVO,
FECHA_RESERVACION_NUEVO,
HORA_RESERVACION_NUEVO,
ESTADO_RESERVACION_NUEVO,
ASIENTO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_RESERVACION,
AUDI_ACCION
)
values
(
new.ID_CLIENTE,new.FECHA_RESERVACION ,new.HORA_RESERVACION,new.ESTADO_RESERVACION,new.ASIENTO,
now(),current_user(),new.ID_RESERVACION ,'Insertar')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_INSERT_RESERVACION_RESERVA_MESA
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_INSERT_RESERVACION_RESERVA_MESA before insert on RESERVACION_RESERVA_MESA
for each row
insert into AUDITORIA_RESERVACION_RESERVA_MESA
(ID_RESERVACION_NUEVO,
ID_MESA_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_RESERVACION_RESERVA_MESA,
AUDI_ACCION
)
values
(new.ID_RESERVACION,new.ID_MESA,
now(),current_user(),new.ID_RESERVACION_RESERVA_MESA ,'Insercion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_INSERT_USUARIO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_INSERT_USUARIO before insert on usuario
for each row
insert into AUDITORIA_USUARIO
(NOMBRE_USUARIO_NUEVO,
CLAVE_USUARIO_NUEVO,
TIPO_USUARIO_NUEVO,
ESTADO_USUARIO_NUEVO,
FOTO_PERFIL_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_USUARIO,
AUDI_ACCION
)
values
(new.NOMBRE_USUARIO,new.CLAVE_USUARIO,new.TIPO_USUARIO,new.ESTADO_USUARIO,new.FOTO_PERFIL,
now(),current_user(),new.ID_USUARIO,'Insercion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_UPDATE_ADMIN
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_UPDATE_ADMIN before update on administrador
for each row
insert into AUDITORIA_ADMIN
(NOMBRE_ADMIN_ANTERIOR,
APELLIDO_ADMIN_ANTERIOR,
EMAIL_ADMIN_ANTERIOR,
CELULAR_ADMIN_ANTERIOR,
ID_USUARIO_ANTERIOR,
NOMBRE_ADMIN_NUEVO,
APELLIDO_ADMIN_NUEVO,
EMAIL_ADMIN_NUEVO,
CELULAR_ADMIN_NUEVO,
ID_USUARIO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_ADMIN,
AUDI_ACCION
)
values
(old.NOMBRE_ADMIN,old.APELLIDO_ADMIN,old.EMAIL_ADMIN,old.CELULAR_ADMIN,old.ID_USUARIO,
new.NOMBRE_ADMIN,new.APELLIDO_ADMIN,new.EMAIL_ADMIN,new.CELULAR_ADMIN,new.ID_USUARIO,
now(),current_user(),new.ID_ADMIN,'Actualizacion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_UPDATE_CATEGORIA_INSUMO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_UPDATE_CATEGORIA_INSUMO before update on CATEGORIA_INSUMO
for each row
insert into AUDITORIA_CATEGORIA_INSUMO
(NOMBRE_CATEGORIA_INSUMO_ANTERIOR,
NOMBRE_CATEGORIA_INSUMO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_CATEGORIA_INSUMO,
AUDI_ACCION
)
values
(old.NOMBRE_CATEGORIA_INSUMO,
new.NOMBRE_CATEGORIA_INSUMO,
now(),current_user(),new.ID_CATEGORIA_INSUMO,'Actualizacion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_UPDATE_CATEGORIA_PRODUCTO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_UPDATE_CATEGORIA_PRODUCTO before update on categoria_producto
for each row
insert into AUDITORIA_CATEGORIA_PRODUCTO
(NOMBRE_CATEGORIA_PRODUCTO_ANTERIOR,
NOMBRE_CATEGORIA_PRODUCTO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_CATEGORIA_PRODUCTO,
AUDI_ACCION
)
values
(old.NOMBRE_CATEGORIA_PRODUCTO,
new.NOMBRE_CATEGORIA_PRODUCTO,
now(),current_user(),ID_CATEGORIA_PRODUCTO,'Actualizacion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_UPDATE_CLIENTE
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_UPDATE_CLIENTE before update on cliente
for each row
insert into AUDITORIA_CLIENTE
(NOMBRE_CLIENTE_ANTERIOR,
APELLIDO_CLIENTE_ANTERIOR,
FECHA_NACIMIENTO_CLIENTE_ANTERIOR,
EMAIL_CLIENTE_ANTERIOR,
CELULAR_CLIENTE_ANTERIOR,
ID_USUARIO_ANTERIOR,
NOMBRE_CLIENTE_NUEVO,
APELLIDO_CLIENTE_NUEVO,
FECHA_NACIMIENTO_CLIENTE_NUEVO,
EMAIL_CLIENTE_NUEVO,
CELULAR_CLIENTE_NUEVO,
ID_USUARIO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_CLIENTE,
AUDI_ACCION
)
values
(old.NOMBRE_CLIENTE,old.APELLIDO_CLIENTE,old.FECHA_NACIMIENTO_CLIENTE,old.EMAIL_CLIENTE,old.CELULAR_CLIENTE,old.ID_USUARIO,
new.NOMBRE_CLIENTE,new.APELLIDO_CLIENTE,new.FECHA_NACIMIENTO_CLIENTE,new.EMAIL_CLIENTE,new.CELULAR_CLIENTE,new.ID_USUARIO,
now(),current_user(),new.ID_CLIENTE,'Actualizacion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_UPDATE_EMPLEADO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_UPDATE_EMPLEADO before update on empleado
for each row
insert into AUDITORIA_EMPLEADO
(DOC_EMPLEADO_ANTERIOR,
NOMBRE_EMPLEADO_ANTERIOR,
APELLIDO_EMPLEADO_ANTERIOR,
EMAIL_EMPLEADO_ANTERIOR,
CELULAR_EMPLEADO_ANTERIOR,
ID_USUARIO_ANTERIOR,
DOC_EMPLEADO_NUEVO,
NOMBRE_EMPLEADO_NUEVO,
APELLIDO_EMPLEADO_NUEVO,
EMAIL_EMPLEADO_NUEVO,
CELULAR_EMPLEADO_NUEVO,
ID_USUARIO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_EMPLEADO,
AUDI_ACCION
)
values
(old.DOC_EMPLEADO,old.NOMBRE_EMPLEADO,old.APELLIDO_EMPLEADO,old.EMAIL_EMPLEADO,old.CELULAR_EMPLEADO,old.ID_USUARIO,
new.DOC_EMPLEADO,new.NOMBRE_EMPLEADO,new.APELLIDO_EMPLEADO,new.EMAIL_EMPLEADO,new.CELULAR_EMPLEADO,new.ID_USUARIO,
now(),current_user(),new.ID_EMPLEADO,'Actualizacion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_UPDATE_INSUMO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_UPDATE_INSUMO before update on insumo
for each row
insert into AUDITORIA_INSUMO
(NOMBRE_INSUMO_ANTERIOR,
CANTIDAD_INSUMO_ANTERIOR,
FECHA_COMPRA_INSUMO_ANTERIOR,
VALOR_INSUMO_ANTERIOR,
ID_PROVEEDOR_ANTERIOR,
ID_CATEGORIA_INSUMO_ANTERIOR,
NOMBRE_INSUMO_NUEVO,
CANTIDAD_INSUMO_NUEVO,
FECHA_COMPRA_INSUMO_NUEVO,
VALOR_INSUMO_NUEVO,
ID_PROVEEDOR_NUEVO,
ID_CATEGORIA_INSUMO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_INSUMO,
AUDI_ACCION
)
values
(old.NOMBRE_INSUMO,old.CANTIDAD_INSUMO,old.FECHA_COMPRA_INSUMO,old.VALOR_INSUMO,old.ID_PROVEEDOR,old.ID_CATEGORIA_INSUMO,
new.NOMBRE_INSUMO,new.CANTIDAD_INSUMO,new.FECHA_COMPRA_INSUMO,new.VALOR_INSUMO,new.ID_PROVEEDOR,new.ID_CATEGORIA_INSUMO,
now(),current_user(),new.ID_INSUMO,'Actualizacion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_UPDATE_PRODUCTO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `AUDITORIA_UPDATE_PRODUCTO` BEFORE UPDATE ON `producto` FOR EACH ROW insert into AUDITORIA_PRODUCTO
(ID_CATEGORIA_PRODUCTO_ANTERIOR,
NOMBRE_PRODUCTO_ANTERIOR,
DESCRIPCION_PRODUCTO_ANTERIOR,
CANTIDAD_PRODUCTO_ANTERIOR,
VALOR_PRODUCTO_ANTERIOR,
IMAGEN_PRODUCTO_ANTERIOR,
ID_CATEGORIA_PRODUCTO_NUEVO,
NOMBRE_PRODUCTO_NUEVO,
DESCRIPCION_PRODUCTO_NUEVO,
CANTIDAD_PRODUCTO_NUEVO,
VALOR_PRODUCTO_NUEVO,
IMAGEN_PRODUCTO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_PRODUCTO,
AUDI_ACCION
)
values
(old.ID_CATEGORIA_PRODUCTO,old.NOMBRE_PRODUCTO,old.DESCRIPCION_PRODUCTO,old.CANTIDAD_PRODUCTO,old.VALOR_PRODUCTO, OLD.IMAGEN_PRODUCTO,
new.ID_CATEGORIA_PRODUCTO,new.NOMBRE_PRODUCTO,new.DESCRIPCION_PRODUCTO,new.CANTIDAD_PRODUCTO,new.VALOR_PRODUCTO, NEW.IMAGEN_PRODUCTO,
now(),current_user(),new.ID_PRODUCTO,'Actualizacion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_UPDATE_PROVEEDOR
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_UPDATE_PROVEEDOR before update on proveedor
for each row
insert into AUDITORIA_PROVEEDOR
(NOMBRE_PROVEEDOR_ANTERIOR,
DIRECCION_PROVEEDOR_ANTERIOR,
PERSONA_ENCARGADA_ANTERIOR,
TELEFONO_PROVEEDOR_ANTERIOR,
NOMBRE_PROVEEDOR_NUEVO,
DIRECCION_PROVEEDOR_NUEVO,
PERSONA_ENCARGADA_NUEVO,
TELEFONO_PROVEEDOR_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_PROVEEDOR,
AUDI_ACCION
)
values
(old.NOMBRE_PROVEEDOR,old.DIRECCION_PROVEEDOR,old.PERSONA_ENCARGADA,old.TELEFONO_PROVEEDOR,
new.NOMBRE_PROVEEDOR,new.DIRECCION_PROVEEDOR,new.PERSONA_ENCARGADA,new.TELEFONO_PROVEEDOR,
now(),current_user(),new.ID_PROVEEDOR,'Actualizacion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_UPDATE_RESERVACION
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_UPDATE_RESERVACION before update on RESERVACION
for each row
insert into AUDITORIA_RESERVACION
(ID_CLIENTE_ANTERIOR,
FECHA_RESERVACION_ANTERIOR,
HORA_RESERVACION_ANTERIOR,
ESTADO_RESERVACION_ANTERIOR,
ASIENTO_ANTERIOR,
ID_CLIENTE_NUEVO,
FECHA_RESERVACION_NUEVO,
HORA_RESERVACION_NUEVO,
ESTADO_RESERVACION_NUEVO,
ASIENTO_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_RESERVACION,
AUDI_ACCION
)
values
(old.ID_CLIENTE,old.FECHA_RESERVACION ,old.HORA_RESERVACION,old.ESTADO_RESERVACION,old.ASIENTO,
new.ID_CLIENTE,new.FECHA_RESERVACION ,new.HORA_RESERVACION,new.ESTADO_RESERVACION,new.ASIENTO,
now(),current_user(),new.ID_RESERVACION ,'Actualizacion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_UPDATE_RESERVACION_RESERVA_MESA
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_UPDATE_RESERVACION_RESERVA_MESA before update on RESERVACION_RESERVA_MESA
for each row
insert into AUDITORIA_RESERVACION_RESERVA_MESA
(ID_RESERVACION_ANTERIOR,
ID_MESA_ANTERIOR,
ID_RESERVACION_NUEVO,
ID_MESA_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_RESERVACION_RESERVA_MESA,
AUDI_ACCION
)
values
(old.ID_RESERVACION,old.ID_MESA,
new.ID_RESERVACION,new.ID_MESA,
now(),current_user(),new.ID_RESERVACION_RESERVA_MESA ,'Actualizacion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador reservaya.AUDITORIA_UPDATE_USUARIO
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER AUDITORIA_UPDATE_USUARIO before update on usuario
for each row
insert into AUDITORIA_USUARIO
(NOMBRE_USUARIO_ANTERIOR,
CLAVE_USUARIO_ANTERIOR,
TIPO_USUARIO_ANTERIOR,
ESTADO_USUARIO_ANTERIOR,
FOTO_PERFIL_ANTERIOR,
NOMBRE_USUARIO_NUEVO,
CLAVE_USUARIO_NUEVO,
TIPO_USUARIO_NUEVO,
ESTADO_USUARIO_NUEVO,
FOTO_PERFIL_NUEVO,
AUDI_FECHA_MODIFICACION,
AUDI_USUARIO,
ID_USUARIO,
AUDI_ACCION
)
values
(old.NOMBRE_USUARIO,old.CLAVE_USUARIO,old.TIPO_USUARIO,old.ESTADO_USUARIO,old.FOTO_PERFIL,
new.NOMBRE_USUARIO,new.CLAVE_USUARIO,new.TIPO_USUARIO,new.ESTADO_USUARIO,new.FOTO_PERFIL,
now(),current_user(),new.ID_USUARIO,'Actualizacion')//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
